sudo: required
services:
  - docker

before_install:
  - docker build -t diegomercury/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run diegomercury/react-test npm test -- --coverage

after_success:
  - docker build -t diegomercury/multi-client ./client
  - docker build -t diegomercury/multi-nginx ./nginx
  - docker build -t diegomercury/multi-server ./server
  - docker build -t diegomercury/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push diegomercury/multi-client
  - docker push diegomercury/multi-nginx
  - docker push diegomercury/multi-server
  - docker push diegomercury/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-228452002632'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'